#!/bin/bash

notebookFile="$1"

if [ "$notebookFile" == "" ]
then
  notebookFile=Notebook.md
fi

tmpFile="/tmp/$notebookFile"
outFile="${notebookFile/\.md/.html}"

if [ ! -f $notebookFile ]
then
  echo No $notebookFile exists.
  exit 1
fi

mkdir -p $(dirname $outFile)

python ParseMarkdown.py "$notebookFile" "$tmpFile"
##pandoc /tmp/Notebook.md -V geometry:margin=1in -o Notebook.pdf
pandoc -s -S --self-contained --toc -H Notebook.css $tmpFile -o $outFile
python ReplaceText.py $outFile "<div id=\"TOC\">" "<h1>Outline</h1>\n<div id=\"TOC\">" $outFile
python ReplaceText.py $outFile "<img" "<img width='800'" $outFile
python RemoveRedundantAnchors.py $outFile

if [ -f $outFile ]
then
  echo $outFile has been created.
fi

rm -f $tmpFile /tmp/${notebookFile}*
