#!/bin/bash

set -o errexit

notebookFile="$1"

if [ "$notebookFile" == "" ]
then
  notebookFile=Notebooks/Notebook.md
fi

tmpFile="${notebookFile/\.md/.tmp}"
outFile="${notebookFile/\.md/.html}"

if [ ! -f $notebookFile ]
then
  echo No $notebookFile exists.
  exit 1
fi

sudo alias pandoc='sudo docker run -t -i -v `pwd`:/workspace ksoichiro/pandoc pandoc'

sudo python ParseMarkdown.py "$notebookFile" "$tmpFile"
##pandoc /tmp/Notebook.md -V geometry:margin=1in -o Notebook.pdf
echo got here 3
sudo pandoc -s -S --self-contained --toc -H Notebook.css $tmpFile -o $outFile
sudo python ReplaceText.py $outFile "<div id=\"TOC\">" "<h1>Outline</h1>\n<div id=\"TOC\">" $outFile
sudo python ReplaceText.py $outFile "<img" "<img width='800'" $outFile
sudo python RemoveRedundantAnchors.py $outFile

if [ -f $outFile ]
then
  echo $outFile has been created.
fi

rm -f $tmpFile
